rules:
  master:
    level: off
  master_excluding_when_with_preceding_slash:
  regex:
    - /(?<!\/)master/g
  level: failure
  slave:
    level: failure
  whitelist:
    level: failure
  blacklist:
    level: failure
