[build]
  base = "book/website"
  command = "pip install -r requirements.txt && jupyter-book build ."
  publish = "_build/html"

# Do not build deploy previews for branches from all-contributors bot
[context.deploy-preview]
  ignore = '''
if echo $HEAD | grep "^all-contributors"; then
  return 0
else
  return 1
fi
'''

# A redirect rule with all the supported properties
[[redirects]]
  from = "https://arron-the-turing-way.netlify.app"
  to = "https://arron-the-turing-way.netlify.app/welcome"
  # The default HTTP status code is 301, but you can define a different one.
  status = 301
  force = true