[build]
  base = "book/website"
  command = "pip install -r requirements.txt && jupyter-book build ."
  publish = "book/website/_build/html"

# Do not build deploy previews for branches from all-contributors bot
[context.deploy-preview]
  ignore = '''
if echo $HEAD | grep "^all-contributors"; then
  return 0
else
  return 1
fi
'''

# A redirect rule with all the supported properties
[[redirects]]
  # Root page changed in https://github.com/alan-turing-institute/the-turing-way/pull/2994
  from = "https://the-turing-way.netlify.app/welcome"
  to = "https://the-turing-way.netlify.app/index.html"
  # The default HTTP status code is 301, but you can define a different one.
  status = 301
  force = true
  
  # A redirect rule with all the supported properties
[[redirects]]
  from = "https://the-turing-way.netlify.app"
  to = "https://the-turing-way.netlify.app/index.html"
  # The default HTTP status code is 301, but you can define a different one.
  status = 301
  force = true

