name: "\U0001F4D6 New Chapter Template"
description: Template for proposing a new chapter
title: 
labels: 
body:
  - type: markdown
    attributes:
      value: "Please complete the following sections when you want to propose a new chapter. If you have write access to the repository, please also assign the appropriate label (or labels) to your issue."
  - type: textarea
    id: summary
    attributes:
      label: Summary of proposed chapter
      description: Please provide a detailed description of the chapter you are writing or proposing. If you have started writing the chapter, also provide details about the pull request you've made as well as the branch you've been working from. Please provide as much context as possible and link to other related issues and pull requests. Consider the following questions
        - What is the name and purpose of your chapter?
        - Why are you proposing it?
        - What Guide is the chapter for?
        - What branch are you working on?
        - Have you made any Pull Requests
- type: textarea
    id: discussion
    attributes:
      label: Discussion points
      description: Use this section to highlight the outcomes of any discussions you have had with regards the development of this chapter. YOU MAY SKIP THIS SECTION
- type: textarea
    id: resources
    attributes:
      label: Resources
      description: List and describe any external resources that may be helpful when writing the chapter. We suggest using bullets (-) and/or checkboxes (-[])
- type: textarea
    id: who_can_help
    attributes:
      label: Who can help?
      description: We suggest using bullets (-) and/or checkboxes (-[])
- type: checkboxes
    id: updates
    attributes:
      label:  Updates
      description: Please update the initial issue with important updates (for example, actions or decisions taken) regularly so that all the important information is available at one glance. You may use the checklist here to get started, feel free to modify this list.
      options:
        - label: Write chapter outline
        - label: Add material to the chapter
        - label: Combine materials into a readable chapter
        - label: Proofread
        - label: Request reviews
        - label: Address reviews
        - label: Merge to main branch
