name: Close talk issues that have happened

on:
  # Manually run the workflow from the Actions page
  workflow_dispatch:
  schedule:
    # Run every Monday at 00:00 UTC
    - cron: "0 0 * * 1"

env:
  # The label assigned to talks issues
  TALK_LABEL: "talks-and-workshops"
  # The label to assign to the new issue reagrding the newsletter
  NEWSLETTER_LABEL: "newsletter"
  # The GitHub handle of the person responsible for collating this info into the
  # newsletter. They will be assigned to the new issue this workflow will create.
  COMMUNITY_MANAGER: "aleesteele"

jobs:
  close-talk-issues:
    runs-on: ubuntu-latest
    permissions:
      # Ensure GITHUB_TOKEN has permissions to create, update, and comment on issues
      issues: write
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install ghapi to interact with the GitHub REST API
        run: |
          pip install ghapi

      - name: Close talk issues that have happened and create a new issue to promote them in the newsletter
        shell: python
        run: |
          from ghapi import GhApi, paged

          # Set variables
          owner, repo = r"""${{ github.repository }}""".split("/")
          talk_label = r"""${{ env.TALK_LABEL }}"""
          newsletter_label = r"""${{ env.NEWSLETTER_LABEL }}"""
          community_manager = r"""${{ env.COMMUNITY_MANAGER }}"""
          github_token = r"""${{ secrets.GITHUB_TOKEN }}"""

          # Authenticate against the GitHub REST API
          api = GhApi(token=github_token)

          # Get all the open issues in the repo that have talk_label
          all_issues = paged(
              api.issues.list_for_repo,
              owner=owner,
              repo=repo,
              state="open",
              labels=talk_label,
              per_page=100,
          )

          # Blank list to store issues to be closed in
          issues_to_close = []

          # Loop over talk issues and determine if they have happened or not yet
          for paged_issues in all_issues:
              for issue in paged_issues:
                  #=== Add in code to extract date from issue body here ===#
                  # body = issue.body

                  #=== Add code to establish if date is in the past or not here ===#
                  # to_be_closed = some_bool_expr

                  if to_be_closed:
                      issue_info = {
                          "repository_url": issue.repository_url,
                          "issue_number": issue.number,
                      }
                      issues_to_close.append(issue_info)

          # Close talk issues that are in the past
          for issue in issues_to_close:
              api.issues.update(
                  owner=owner,
                  repo=repo,
                  issue_number=issue["issue_number"],
                  state="closed",
              )

          # Construct Markdown text listing all the issues that have been closed
          body = (
              "Please add the following talks to the next newsletter!\n\n"
              + "\n".join([f"- {issue['repository_url']}" for issue in issues_to_close])
          )

          # Check if a newsletter issue is already open
          all_issues = paged(
              api.issues.list_for_repo,
              owner=owner,
              repo=repo,
              state="open",
              creator="github-actions[bot]",
              labels=newsletter_label,
              per_page=100,
          )

          for paged_issues in all_issues:
              if paged_issues:
                  create_new_issue = False
                  # We take the number of the first returned issue here
                  issue_number = paged_issues[0].number
              else:
                  create_new_issue = True
                  issue_number = None
              break

          if create_new_issue:
              # An issue doesn't exist, create one
              api.issues.create(
                  owner=owner,
                  repo=repo,
                  title="Recent talks to promote in the newsletter",
                  body=body,
                  labels=newsletter_label,
                  assignee=community_manager,
              )
          else:
              # An issue exists, add list of newly closed issues as a comment
              api.issues.create_comment(
                  owner=owner,
                  repo=repo,
                  issue_number=issue_number,
                  body=body,
              )
