name: Lint and Validate YAML files

on:
  push:
    paths:
      - "**.yaml"
      - "**.yml"

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install yamllint
        run: |
          python -m pip install yamllint

      - name: Run yamllint and all files in the repo
        run: |
          yamllint -f colored .
